// Code generated by "stringer -type=EventType"; DO NOT EDIT

package kv

import "fmt"

const _EventType_name = "NoneCreateDeleteUpdate"

var _EventType_index = [...]uint8{0, 4, 10, 16, 22}

func (i EventType) String() string {
	if i < 0 || i >= EventType(len(_EventType_index)-1) {
		return fmt.Sprintf("EventType(%d)", i)
	}
	return _EventType_name[_EventType_index[i]:_EventType_index[i+1]]
}
